name: Deploy website to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to InfinityFree via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/**
